//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryptonApplicationUpdater.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class ThemeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ThemeSettings defaultInstance = ((ThemeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ThemeSettings())));
        
        public static ThemeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomTheme {
            get {
                return ((bool)(this["UseCustomTheme"]));
            }
            set {
                this["UseCustomTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2007BlackTheme {
            get {
                return ((bool)(this["UseOffice2007BlackTheme"]));
            }
            set {
                this["UseOffice2007BlackTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2007BlueTheme {
            get {
                return ((bool)(this["UseOffice2007BlueTheme"]));
            }
            set {
                this["UseOffice2007BlueTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2007SilverTheme {
            get {
                return ((bool)(this["UseOffice2007SilverTheme"]));
            }
            set {
                this["UseOffice2007SilverTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2010BlackTheme {
            get {
                return ((bool)(this["UseOffice2010BlackTheme"]));
            }
            set {
                this["UseOffice2010BlackTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseOffice2010BlueTheme {
            get {
                return ((bool)(this["UseOffice2010BlueTheme"]));
            }
            set {
                this["UseOffice2010BlueTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2010SilverTheme {
            get {
                return ((bool)(this["UseOffice2010SilverTheme"]));
            }
            set {
                this["UseOffice2010SilverTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2013Theme {
            get {
                return ((bool)(this["UseOffice2013Theme"]));
            }
            set {
                this["UseOffice2013Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOffice2013WhiteTheme {
            get {
                return ((bool)(this["UseOffice2013WhiteTheme"]));
            }
            set {
                this["UseOffice2013WhiteTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSparkleBlueTheme {
            get {
                return ((bool)(this["UseSparkleBlueTheme"]));
            }
            set {
                this["UseSparkleBlueTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSparkleOrangeTheme {
            get {
                return ((bool)(this["UseSparkleOrangeTheme"]));
            }
            set {
                this["UseSparkleOrangeTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSparklePurpleTheme {
            get {
                return ((bool)(this["UseSparklePurpleTheme"]));
            }
            set {
                this["UseSparklePurpleTheme"] = value;
            }
        }
    }
}
