//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColourCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{0}using System.Drawing;
using System.Windows.Forms;

namespace {1}
{{
    class {2} : ProfessionalColorTable
    {{
        public override Color ButtonSelectedHighlight
        {{
            get {{ return ButtonSelectedGradientMiddle; }}
        }}
        public override Color ButtonSelectedHighlightBorder
        {{
            get {{ return ButtonSelectedBorder; }}
        }}
        public override Color ButtonPressedHighlight
        {{
            get {{ return ButtonPressedGradientMiddle; }}
        }}
        public override Color ButtonPressedHighlightBorder
        {{
            get {{ return ButtonPressedBorder; }}
        }}
        public override Color ButtonCheckedHighlight
        {{
            get {{ return ButtonCheckedGradientMiddle; }}
        }}
        public override Color ButtonCheckedHighlightBorder
        {{
            get {{ return ButtonSelectedBorder; }}
        }}
        public override Color ButtonPressedBorder
        {{
            get {{ return ButtonSelectedBorder; }}
        }}
{3}    }}
}}")]
        public string Template {
            get {
                return ((string)(this["Template"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("        public override Color {0}\r\n        {{ \r\n            get {{ return Color.F" +
            "romArgb({1}, {2}, {3}, {4}); }}\r\n        }}")]
        public string PropertyTemplateArgb {
            get {
                return ((string)(this["PropertyTemplateArgb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ColourHeight {
            get {
                return ((int)(this["ColourHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int ColourWidth {
            get {
                return ((int)(this["ColourWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("        public override Color {0}\r\n        {{ \r\n            get {{ return Color.F" +
            "romName(\"{1}\"); }}\r\n        }}")]
        public string PropertyTemplateName {
            get {
                return ((string)(this["PropertyTemplateName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MyNamespace")]
        public string DefaultNamespace {
            get {
                return ((string)(this["DefaultNamespace"]));
            }
            set {
                this["DefaultNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{0}Imports System.Drawing
Imports System.Windows.Forms

Namespace {1}
	Class {2}
		Inherits ProfessionalColorTable
		Public Overrides ReadOnly Property ButtonSelectedHighlight() As Color
			Get
				Return ButtonSelectedGradientMiddle
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonSelectedHighlightBorder() As Color
			Get
				Return ButtonSelectedBorder
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonPressedHighlight() As Color
			Get
				Return ButtonPressedGradientMiddle
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonPressedHighlightBorder() As Color
			Get
				Return ButtonPressedBorder
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonCheckedHighlight() As Color
			Get
				Return ButtonCheckedGradientMiddle
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonCheckedHighlightBorder() As Color
			Get
				Return ButtonSelectedBorder
			End Get
		End Property
		Public Overrides ReadOnly Property ButtonPressedBorder() As Color
			Get
				Return ButtonSelectedBorder
			End Get
		End Property
{3}	End Class
End Namespace")]
        public string TemplateVB {
            get {
                return ((string)(this["TemplateVB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t\tPublic Overrides ReadOnly Property {0}() As Color\r\n\t\t\tGet\r\n\t\t\t\tReturn Color.Fro" +
            "mArgb({1}, {2}, {3}, {4})\r\n\t\t\tEnd Get\r\n\t\tEnd Property")]
        public string PropertyTemplateNameVB {
            get {
                return ((string)(this["PropertyTemplateNameVB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} <auto-generated>\r\n{0}     This code was generated by .NET ToolStrip Customize" +
            "r.\r\n{0}     http://toolstripcustomizer.codeplex.com/\r\n{0} </auto-generated>\r\n\r\n")]
        public string AutoGeneratedHeader {
            get {
                return ((string)(this["AutoGeneratedHeader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'")]
        public string CommentVB {
            get {
                return ((string)(this["CommentVB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//")]
        public string CommentCS {
            get {
                return ((string)(this["CommentCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\t\tPublic Overrides ReadOnly Property {0}() As Color\r\n\t\t\tGet\r\n\t\t\t\tReturn Color.Fro" +
            "mArgb({1}, {2}, {3}, {4})\r\n\t\t\tEnd Get\r\n\t\tEnd Property")]
        public string PropertyTemplateArgbVB {
            get {
                return ((string)(this["PropertyTemplateArgbVB"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeHeader {
            get {
                return ((bool)(this["IncludeHeader"]));
            }
            set {
                this["IncludeHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RoundedEdges {
            get {
                return ((bool)(this["RoundedEdges"]));
            }
            set {
                this["RoundedEdges"] = value;
            }
        }
    }
}
