//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tooling.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class ColourSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColourSettings defaultInstance = ((ColourSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColourSettings())));
        
        public static ColourSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BaseColour {
            get {
                return ((global::System.Drawing.Color)(this["BaseColour"]));
            }
            set {
                this["BaseColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DarkestColour {
            get {
                return ((global::System.Drawing.Color)(this["DarkestColour"]));
            }
            set {
                this["DarkestColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MediumColour {
            get {
                return ((global::System.Drawing.Color)(this["MediumColour"]));
            }
            set {
                this["MediumColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightColour {
            get {
                return ((global::System.Drawing.Color)(this["LightColour"]));
            }
            set {
                this["LightColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightestColour {
            get {
                return ((global::System.Drawing.Color)(this["LightestColour"]));
            }
            set {
                this["LightestColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BorderColour {
            get {
                return ((global::System.Drawing.Color)(this["BorderColour"]));
            }
            set {
                this["BorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["NormalTextColour"]));
            }
            set {
                this["NormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledTextColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledTextColour"]));
            }
            set {
                this["DisabledTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledColour"]));
            }
            set {
                this["DisabledColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkNormalColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkNormalColour"]));
            }
            set {
                this["LinkNormalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int AlphaChannelValue {
            get {
                return ((int)(this["AlphaChannelValue"]));
            }
            set {
                this["AlphaChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RedChannelValue {
            get {
                return ((int)(this["RedChannelValue"]));
            }
            set {
                this["RedChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GreenChannelValue {
            get {
                return ((int)(this["GreenChannelValue"]));
            }
            set {
                this["GreenChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BlueChannelValue {
            get {
                return ((int)(this["BlueChannelValue"]));
            }
            set {
                this["BlueChannelValue"] = value;
            }
        }
    }
}
