//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tooling.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class PaletteThemeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PaletteThemeSettings defaultInstance = ((PaletteThemeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PaletteThemeSettings())));
        
        public static PaletteThemeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Global")]
        public global::ComponentFactory.Krypton.Toolkit.PaletteMode Theme {
            get {
                return ((global::ComponentFactory.Krypton.Toolkit.PaletteMode)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomThemeFilePath {
            get {
                return ((string)(this["CustomThemeFilePath"]));
            }
            set {
                this["CustomThemeFilePath"] = value;
            }
        }
    }
}
