//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitSettings.Settings.Global {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class GlobalStringSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalStringSettings defaultInstance = ((GlobalStringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalStringSettings())));
        
        public static GlobalStringSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BasePaletteMode {
            get {
                return ((string)(this["BasePaletteMode"]));
            }
            set {
                this["BasePaletteMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This will become informative...")]
        public string FeedbackText {
            get {
                return ((string)(this["FeedbackText"]));
            }
            set {
                this["FeedbackText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaletteExportPath {
            get {
                return ((string)(this["PaletteExportPath"]));
            }
            set {
                this["PaletteExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD5 Files, RIPEMD-160 Files, SHA-1 Files, SHA-256 Files, SHA-384 Files, SHA-512 F" +
            "iles, All Files")]
        public string HashReadableFileTypesFilterList {
            get {
                return ((string)(this["HashReadableFileTypesFilterList"]));
            }
            set {
                this["HashReadableFileTypesFilterList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".md5,.ripemd160,.sha1,.sha256,.sha384,.sha512,.*")]
        public string HashFileTypeExtensionList {
            get {
                return ((string)(this["HashFileTypeExtensionList"]));
            }
            set {
                this["HashFileTypeExtensionList"] = value;
            }
        }
    }
}
