//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitResources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimeSpanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeSpanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolkitResources.Strings.TimeSpanResources", typeof(TimeSpanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day,day,d.
        /// </summary>
        internal static string TimeSpanDayStrings {
            get {
                return ResourceManager.GetString("TimeSpanDayStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours,hour,hrs,hr,h.
        /// </summary>
        internal static string TimeSpanHourStrings {
            get {
                return ResourceManager.GetString("TimeSpanHourStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%w&apos;w&apos;]_[%r&apos;d&apos;]_[%h&apos;h&apos;]_[%m&apos;m&apos;]_[%s&apos;s&apos;].
        /// </summary>
        internal static string TimeSpanJiraFormat {
            get {
                return ResourceManager.GetString("TimeSpanJiraFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%w\w][_][%d\d][_][%h\h][_][%m\m][_][%s\s].
        /// </summary>
        internal static string TimeSpanJiraPattern {
            get {
                return ResourceManager.GetString("TimeSpanJiraPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string TimeSpanManyDayFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string TimeSpanManyHourFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string TimeSpanManyMillisecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyMillisecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string TimeSpanManyMinuteFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string TimeSpanManySecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanManySecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticks.
        /// </summary>
        internal static string TimeSpanManyTickFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyTickFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds,millisecond,ms.
        /// </summary>
        internal static string TimeSpanMillisecondStrings {
            get {
                return ResourceManager.GetString("TimeSpanMillisecondStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes,minute,mins,min,m.
        /// </summary>
        internal static string TimeSpanMinuteStrings {
            get {
                return ResourceManager.GetString("TimeSpanMinuteStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string TimeSpanOneDayFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string TimeSpanOneHourFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millisecond.
        /// </summary>
        internal static string TimeSpanOneMillisecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneMillisecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string TimeSpanOneMinuteFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string TimeSpanOneSecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneSecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick.
        /// </summary>
        internal static string TimeSpanOneTickFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneTickFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds,second,secs,sec,s.
        /// </summary>
        internal static string TimeSpanSecondStrings {
            get {
                return ResourceManager.GetString("TimeSpanSecondStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string TimeSpanSeparator {
            get {
                return ResourceManager.GetString("TimeSpanSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tick,tick,t.
        /// </summary>
        internal static string TimeSpanTickStrings {
            get {
                return ResourceManager.GetString("TimeSpanTickStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%d_@d],[%h_@h],[%m_@m],[%s_@s],[%k_@k].
        /// </summary>
        internal static string TimeSpanWordFormat {
            get {
                return ResourceManager.GetString("TimeSpanWordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [%d_@d][_][\,][_][%h_@h][_][\,][_][%m_@m][_][\,][_][%s_@s][_][\,][_][%k_@k][_][\,][_][%t_@t].
        /// </summary>
        internal static string TimeSpanWordPattern {
            get {
                return ResourceManager.GetString("TimeSpanWordPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string TimeSpanWordPatternIgnoreCase {
            get {
                return ResourceManager.GetString("TimeSpanWordPatternIgnoreCase", resourceCulture);
            }
        }
    }
}
