//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Settings.Colours.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class BasicPaletteColours : global::System.Configuration.ApplicationSettingsBase {
        
        private static BasicPaletteColours defaultInstance = ((BasicPaletteColours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BasicPaletteColours())));
        
        public static BasicPaletteColours Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BaseColour {
            get {
                return ((global::System.Drawing.Color)(this["BaseColour"]));
            }
            set {
                this["BaseColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DarkestColour {
            get {
                return ((global::System.Drawing.Color)(this["DarkestColour"]));
            }
            set {
                this["DarkestColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightColour {
            get {
                return ((global::System.Drawing.Color)(this["LightColour"]));
            }
            set {
                this["LightColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LightestColour {
            get {
                return ((global::System.Drawing.Color)(this["LightestColour"]));
            }
            set {
                this["LightestColour"] = value;
            }
        }
    }
}
