//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Settings.Colours.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class CustomPaletteColours : global::System.Configuration.ApplicationSettingsBase {
        
        private static CustomPaletteColours defaultInstance = ((CustomPaletteColours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CustomPaletteColours())));
        
        public static CustomPaletteColours Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourOne {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourOne"]));
            }
            set {
                this["CustomColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourTwo"]));
            }
            set {
                this["CustomColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourThree {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourThree"]));
            }
            set {
                this["CustomColourThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFour {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFour"]));
            }
            set {
                this["CustomColourFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CustomColourFive {
            get {
                return ((global::System.Drawing.Color)(this["CustomColourFive"]));
            }
            set {
                this["CustomColourFive"] = value;
            }
        }
    }
}
