//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Settings.Colours.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class LinkTextPaletteColours : global::System.Configuration.ApplicationSettingsBase {
        
        private static LinkTextPaletteColours defaultInstance = ((LinkTextPaletteColours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LinkTextPaletteColours())));
        
        public static LinkTextPaletteColours Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkDisabledColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkDisabledColour"]));
            }
            set {
                this["LinkDisabledColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkFocusedColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkFocusedColour"]));
            }
            set {
                this["LinkFocusedColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkNormalColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkNormalColour"]));
            }
            set {
                this["LinkNormalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkHoverColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkHoverColour"]));
            }
            set {
                this["LinkHoverColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LinkVisitedColour {
            get {
                return ((global::System.Drawing.Color)(this["LinkVisitedColour"]));
            }
            set {
                this["LinkVisitedColour"] = value;
            }
        }
    }
}
