//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Settings.Colours.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class TextPaletteColours : global::System.Configuration.ApplicationSettingsBase {
        
        private static TextPaletteColours defaultInstance = ((TextPaletteColours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TextPaletteColours())));
        
        public static TextPaletteColours Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color AlternativeNormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["AlternativeNormalTextColour"]));
            }
            set {
                this["AlternativeNormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DisabledTextColour {
            get {
                return ((global::System.Drawing.Color)(this["DisabledTextColour"]));
            }
            set {
                this["DisabledTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color NormalTextColour {
            get {
                return ((global::System.Drawing.Color)(this["NormalTextColour"]));
            }
            set {
                this["NormalTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color FocusedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["FocusedTextColour"]));
            }
            set {
                this["FocusedTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PressedTextColour {
            get {
                return ((global::System.Drawing.Color)(this["PressedTextColour"]));
            }
            set {
                this["PressedTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color RibbonTabTextColour {
            get {
                return ((global::System.Drawing.Color)(this["RibbonTabTextColour"]));
            }
            set {
                this["RibbonTabTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color MenuTextColour {
            get {
                return ((global::System.Drawing.Color)(this["MenuTextColour"]));
            }
            set {
                this["MenuTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color StatusStripTextColour {
            get {
                return ((global::System.Drawing.Color)(this["StatusStripTextColour"]));
            }
            set {
                this["StatusStripTextColour"] = value;
            }
        }
    }
}
