//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitControlSettings.Settings.Toolkit.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class CommonKryptonControlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommonKryptonControlSettings defaultInstance = ((CommonKryptonControlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommonKryptonControlSettings())));
        
        public static CommonKryptonControlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font LongTextTypeface {
            get {
                return ((global::System.Drawing.Font)(this["LongTextTypeface"]));
            }
            set {
                this["LongTextTypeface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font ShortTextTypeface {
            get {
                return ((global::System.Drawing.Font)(this["ShortTextTypeface"]));
            }
            set {
                this["ShortTextTypeface"] = value;
            }
        }
    }
}
