//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitControlSettings.Settings.Toolkit.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class KryptonCheckedListBoxCommonSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KryptonCheckedListBoxCommonSettings defaultInstance = ((KryptonCheckedListBoxCommonSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KryptonCheckedListBoxCommonSettings())));
        
        public static KryptonCheckedListBoxCommonSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BackgroundColourOne {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColourOne"]));
            }
            set {
                this["BackgroundColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color BackgroundColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColourTwo"]));
            }
            set {
                this["BackgroundColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ItemBackgroundColourOne {
            get {
                return ((global::System.Drawing.Color)(this["ItemBackgroundColourOne"]));
            }
            set {
                this["ItemBackgroundColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ItemBackgroundColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["ItemBackgroundColourTwo"]));
            }
            set {
                this["ItemBackgroundColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LongTextColourOne {
            get {
                return ((global::System.Drawing.Color)(this["LongTextColourOne"]));
            }
            set {
                this["LongTextColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LongTextColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["LongTextColourTwo"]));
            }
            set {
                this["LongTextColourTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ShortTextColourOne {
            get {
                return ((global::System.Drawing.Color)(this["ShortTextColourOne"]));
            }
            set {
                this["ShortTextColourOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ShortTextColourTwo {
            get {
                return ((global::System.Drawing.Color)(this["ShortTextColourTwo"]));
            }
            set {
                this["ShortTextColourTwo"] = value;
            }
        }
    }
}
