//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolkitSettings.Settings.Global {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class GlobalBooleanSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalBooleanSettings defaultInstance = ((GlobalBooleanSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalBooleanSettings())));
        
        public static GlobalBooleanSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsInDeveloperMode {
            get {
                return ((bool)(this["IsInDeveloperMode"]));
            }
            set {
                this["IsInDeveloperMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutomaticallyUpdateColours {
            get {
                return ((bool)(this["AutomaticallyUpdateColours"]));
            }
            set {
                this["AutomaticallyUpdateColours"] = value;
            }
        }
    }
}
